# Generated by Django 4.1.13 on 2024-03-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Product",
            },
        ),
        migrations.CreateModel(
            name="ProduitEnPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("tigID", models.IntegerField(default="-1")),
            ],
            options={
                "ordering": ("tigID",),
            },
        ),
        migrations.CreateModel(
            name="ProduitValid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("tigID", models.IntegerField(default="-1")),
            ],
            options={
                "ordering": ("tigID",),
            },
        ),
    ]
