# Generated by Django 4.1.13 on 2024-03-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("category", models.IntegerField()),
                ("price", models.FloatField()),
                ("unit", models.CharField(default="Kg", max_length=2)),
                ("availability", models.BooleanField()),
                ("sale", models.BooleanField()),
                ("discount", models.DecimalField(decimal_places=2, max_digits=3)),
                ("comments", models.TextField(blank=True, max_length=100, null=True)),
                ("owner", models.CharField(default="tig", max_length=3)),
            ],
            options={
                "db_table": "Produit",
            },
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
