# Generated by Django 4.1.13 on 2024-03-16 21:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0002_produit_delete_product"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="produit",
            table=None,
        ),
    ]
