# Generated by Django 4.1.13 on 2024-03-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0004_alter_produit_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="produit",
            name="category",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="sale",
        ),
        migrations.AlterField(
            model_name="produit",
            name="availability",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="produit",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="produit",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="produit",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="produit",
            name="unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
