# Generated by Django 4.1.13 on 2024-03-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0006_alerte"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pourcentage_reduction",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poissonerieapp.produit",
                    ),
                ),
            ],
        ),
    ]
