# Generated by Django 4.1.13 on 2024-03-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0008_utilisateur"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
                ("prix_vente", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_vente", models.DateField(auto_now_add=True)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poissonerieapp.produit",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poissonerieapp.utilisateur",
                    ),
                ),
            ],
        ),
    ]
