# Generated by Django 4.1.13 on 2024-03-17 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0011_kpi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produit",
            old_name="name",
            new_name="nom",
        ),
        migrations.RenameField(
            model_name="produit",
            old_name="discount",
            new_name="pourcentage_promo",
        ),
        migrations.RenameField(
            model_name="produit",
            old_name="price",
            new_name="prix",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="unit",
        ),
        migrations.AddField(
            model_name="produit",
            name="categorie",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="poissonerieapp.categorieproduit",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produit",
            name="commentaire",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produit",
            name="nombre_articles_vendus",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produit",
            name="prix_promo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="quantite_stock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
