# Generated by Django 4.1.13 on 2024-03-17 22:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0012_rename_name_produit_nom_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Alerte",
        ),
        migrations.DeleteModel(
            name="KPI",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="vente",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="vente",
            name="utilisateur",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="categorie",
        ),
        migrations.DeleteModel(
            name="Promotion",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.DeleteModel(
            name="Utilisateur",
        ),
        migrations.DeleteModel(
            name="Vente",
        ),
    ]
