# Generated by Django 4.1.13 on 2024-03-17 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "poissonerieapp",
            "0013_delete_alerte_delete_kpi_remove_transaction_produit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="categorie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="poissonerieapp.categorieproduit",
            ),
        ),
    ]
