# Generated by Django 4.1.13 on 2024-03-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0014_produit_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="quantite_stock",
            field=models.IntegerField(default=0),
        ),
    ]
