# Generated by Django 4.1.13 on 2024-03-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0016_alter_produit_nombre_articles_vendus"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="unite",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
