# Generated by Django 4.1.13 on 2024-03-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0017_produit_unite"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="disponible",
            field=models.BooleanField(default=False),
        ),
    ]
