# Generated by Django 4.1.13 on 2024-03-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0018_produit_disponible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorieproduit",
            name="id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
