# Generated by Django 4.1.13 on 2024-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0019_alter_categorieproduit_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorieproduit",
            name="value",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="categorieproduit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
