# Generated by Django 4.1.13 on 2024-03-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0023_alerte"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chiffre_affaires",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("marge", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "impot_societes",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("trimestre", models.IntegerField()),
                ("annee", models.IntegerField()),
            ],
        ),
    ]
