# Generated by Django 4.1.13 on 2024-03-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0025_transaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produit",
            old_name="disponible",
            new_name="availability",
        ),
        migrations.RenameField(
            model_name="produit",
            old_name="nombre_articles_vendus",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="produit",
            old_name="nom",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="produit",
            old_name="unite",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="produit",
            old_name="prix",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="categorie",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="commentaire",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="pourcentage_promo",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="prix_promo",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="quantite_stock",
        ),
        migrations.AddField(
            model_name="produit",
            name="sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="produit",
            name="unit",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
