# Generated by Django 4.1.13 on 2024-03-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poissonerieapp", "0026_rename_disponible_produit_availability_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="comments",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="produit",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
