# Generated by Django 4.1.13 on 2024-03-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poissonerieapp', '0027_produit_comments_produit_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
